### ISSUE TITLE
RSocket.io down

### ISSUE THREAD

**Issue by derTobsch** [rsocket/rsocket-website#30]
https://rsocket.io/ is not available there is just a 
![rsocket](https://user-images.githubusercontent.com/5683677/108824785-6b588280-75c2-11eb-888f-4a423a7bba51.png)

**Comment by derTobsch** [comment]
ping @OlegDokuka :-)

**Comment by viglucci** [comment]
Yikes. Sorry for this. Looking into it now.

**Comment by viglucci** [comment]
Addressed by #35 . Thanks!
